apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auralive-dev

bases:
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: auralive-web
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: web
              resources:
                requests:
                  cpu: "100m"
                  memory: "256Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"

configMapGenerator:
  - name: auralive-config
    behavior: merge
    literals:
      - APP_ENV=development
      - NODE_ENV=development
      - PAYMENT_GATEWAY_PROVIDER=ccbill_mock
      - KYC_PROVIDER=persona_mock
      - LIVESTREAM_PROVIDER=livepeer_mux_mock
      - ENABLE_DEBUG_ENDPOINTS=true
